spring:
  thymeleaf:
    # 关闭缓存
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=Asia/Shanghai
    username: root
    password: Vivian
    hikari:
      # 连接池名
      pool-name: DateHikaruCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间,默认十分钟
      idle-timeout: 180000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认半小时
      max-lifetime: 1800000
      # 连接超时时间，默认30秒
      connection-timeout: 30000
      # 测试连接是否可用的查询语句，类似心跳机制
      connection-test-query: SELECT 1
  redis:
    timeout: 6000ms
    password: foobared
    cluster:
      nodes:
        - 127.0.0.1:6379
        - 127.0.0.1:6380
        - 127.0.0.1:6381
        - 127.0.0.1:6382
        - 127.0.0.1:6383
        - 127.0.0.1:6384
      # 获取失败之后最大重定向次数
      max-redirects: 3
    lettuce:
      pool:
        # 最大连接数：8，使用负值表示没有限制
        max-active: 1000
        # 最大连接阻塞等待时间，默认-1，负数表示没有限制
        max-wait: 5000ms
        # 最大空闲连接，默认8
        max-idle: 20
        # 最小空闲连接，默认0
        min-idle: 10

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置MyBatis数据返回类型别名，默认别名是类名
  type-aliases-package: com.vi.seckill.pojo

logging:
  level:
    com.vi.seckill.mapper: debug